### PR TITLE
remove unused OneBusAway-iPhone IRC channel

### PR DESCRIPTION
**Pull request by bbodenmiller**
Does not appear to be used & Gitter looks to be much better.

### CODE REVIEW

**Comment by aaronbrethorst** [comment]
:+1:

**Comment by bbodenmiller** [comment]
@aaronbrethorst do you think you'll have a chance to enable Gitter [GitHub, Travis CI, & Huboard integrations](https://gitter.zendesk.com/hc/en-us/articles/200176722-Integrations) for the hackathon?

**Comment by barbeau** [comment]
Let me know if you get the Travis hooks working for Gitter.  A few builds showed up in OBA Android Gitter room but then went silent.  Not sure if I have it configured right.

**Comment by aaronbrethorst** [comment]
@barbeau check the value of the `on_success` key. I bet you that if it's set to `change`, it'll go quiet until there's a change in the success status. I'm setting iOS' to `always`

**Comment by barbeau** [comment]
IIRC it's ´change´, but build failures is ´always´, and those weren't
showing up either.  And neither were successes after failures.  But that's
a good idea to troubleshoot at any rate, will give it a shot.

**Comment by aaronbrethorst** [comment]
Hmm, bummer. No idea, then :(

**Pull request merged**
