### PR TITLE
Stop showing already-departed buses

### LINKED ISSUE #864: Improve explanation of negative minutes
- [ ] Design
- [ ] Implementation
-----

img_1371

### PR DESCRIPTION
**Pull request by aaronbrethorst**
Fixes #864

### CODE REVIEW

**Comment by barbeau** [comment]
;)

https://groups.google.com/d/msg/onebusaway-developers/pVxORUgLhe0/_e01oXDEYSUJ

**Comment by aaronbrethorst** [comment]
That's pretty funny. I'd forgotten about that :) I still think it has merit, but if the majority of users find it confusing, I'm not going to argue with them. I see enable/disable checkboxes as being a path of last resort. I'll do it if necessary, but don't want to go right for that.

**Comment by barbeau** [comment]
Yeah, I get it, I had the same internal dialog on Android.  My final conclusion was I didn't want to yank something from the UI that had been there from the beginning because of a (relatively) small number of vocal users complaining about not understanding it.  My guess was that far more users found it valuable than confusing, but we just hear about the users that find it confusing (many of which may be new to the app and adjusting to the entire UI).  But, that's just a guess - it does come down to a estimate of what the majority of users think.  Ultimately it's your call on iOS.

**Comment by aaronbrethorst** [comment]
If I get complaints in the opposite direction I will certainly put it back. I just want to minimize the amount of reading that users have to engage in in order to get the information they want.

**Pull request merged**
