### PR TITLE
Merge 2.3.1 into master

### PR DESCRIPTION
**Pull request by caitbonnar**
I'm releasing a hotfix for the out of region alert always popping up for some users (#340). I've tested the fix with 3 of the users who originally reported the issue and all say it is fixed now, so I believe this is ready for immediate release. (Plus we won't be able to submit any apps during Dec 22-29 due to some maintenance on Apple's end.)

Will pull this in once it is submitted.

### CODE REVIEW

**Comment by bbodenmiller** [comment]
Good news: Since this was released (Jan 2), Out of Region alerts are down significantly:

image
image
image

**Comment by barbeau** [comment]
Nice!

**Comment by caitbonnar** [comment]
I noticed that as well. Thanks, @Wizecoder! :)

**Comment by Wizecoder** [comment]
Phew, glad it worked!

**Pull request merged**
