### PR TITLE
Fixed a linker error while building a unit test target

### PR DESCRIPTION
**Pull request by nullp0inter**
Added OBAURLHelpers.m file to the test target. Used to fail with linker error like: "Undefined symbols for architecture x86_64: _OBJC_CLASS_$_OBAURLHelpers"

### CODE REVIEW

**Comment by aaronbrethorst** [comment]
We shouldn't need to add any m files to the test target. Which version of Xcode are you using?

**Comment by nullp0inter** [comment]
Xcode Version 6.1.1

**Comment by nullp0inter** [comment]
Reproducible for AppStoreRelease scheme only. Travis uses the Debug one. That is why the CI is green.

**Comment by bbodenmiller** [comment]
How can we update Travis to pickup this error?

**Comment by nullp0inter** [comment]
Changed the Travis CI script accordingly.

**Comment by aaronbrethorst** [comment]
Merged in #371

**Pull request closed without merging**
