### PR TITLE
Fix develop to be able to merge to master

### PR DESCRIPTION
**Pull request by bbodenmiller**
Fixed git merging issues mentioned at https://github.com/OneBusAway/onebusaway-iphone/pull/377#issuecomment-76869208.

Verify fix at: https://github.com/OneBusAway/onebusaway-iphone/compare/OneBusAway:master...bbodenmiller:fix-develop?expand=1
Verify that it is currently broken at: https://github.com/OneBusAway/onebusaway-iphone/compare/OneBusAway:master...OneBusAway:develop?expand=1

### CODE REVIEW

**Comment by bbodenmiller** [comment]
Failure is because iOS 7 SDK does not know how to compile the new alert.

**Comment by aaronbrethorst** [comment]
iOS 7 SDK can't compile, or iOS 7 simulator can't run it?

**Comment by aaronbrethorst** [comment]
@bbodenmiller can you update this PR with the fix for the iOS 7 issue?

**Comment by bbodenmiller** [comment]
Travis is running still but should be good to go.

**Comment by aaronbrethorst** [comment]
Thanks!

**Pull request merged**
