### PR TITLE
Improve Travis CI to also test iOS 7

### PR DESCRIPTION
**Pull request by bbodenmiller**
Dependent on/merges #371.

Update Travis CI to test iOS 7. Note I am submitted this with a failing test as failure appears to be related to an actual problem rather than the Travis CI test setup.

### CODE REVIEW

**Comment by aaronbrethorst** [comment]
I'll check this out in the AM. thanks!

**Comment by aaronbrethorst** [comment]
@bbodenmiller deleting the one place where `-measureBlock:` is called in the tests should resolve this.

**Comment by bbodenmiller** [comment]
Sweet. Looks to be passing now.

**Comment by bbodenmiller** [comment]
@aaronbrethorst is your understanding that `iphonesimulator7.0` tests that the app runs on iOS 7 or rather that it can build the source against the iOS 7 SDK? Do we care if it builds against the iOS 7 SDK as long as it just runs on iOS 7?

**Comment by aaronbrethorst** [comment]
Excellent question, and—as you can see from my last comment—one I was just thinking about too :)

`iphonesimulator7.0` refers to the simulator not the building SDK version. What's weird, though, is that I ran this locally in the iOS 7 simulator last night without trouble. So I'm not clear on the exact issue.

**Comment by bbodenmiller** [comment]
Per https://travis-ci.org/bbodenmiller/onebusaway-iphone/builds/52930937 this resulted in a failing test when merged.

**Comment by bbodenmiller** [comment]
From [xcodebuild(1) Mac OS X Developer Tools Manual Page](https://developer.apple.com/library/mac/documentation/Darwin/Reference/ManPages/man1/xcodebuild.1.html):

> -sdk [\<sdkfullpath\> | \<sdkname\>]
>            Build an Xcode project or workspace against the specified SDK, using build tools appropriate for that SDK. The argument may be an absolute path to an SDK, or the canonical name of an SDK.

So I think it is trying to build using the iOS 7 SDK. Should we revert https://github.com/OneBusAway/onebusaway-iphone/commit/0b3cb244cc9fcd9fdc6650da1a38e6867f9757fc?

**Comment by aaronbrethorst** [comment]
How interesting. I think you're right and I stand corrected. Yeah that should be reverted.

**Pull request merged**
