### PR TITLE
Replaced the location and list icons with nicer ones.

### PR DESCRIPTION
**Pull request by yogipatel**
Thought the default ones were a bit blurry and out of place. These icons are extracted from iOS itself, so shouldn't need any attibution (I think). Includes `@3x` images.

### CODE REVIEW

**Comment by yogipatel** [comment]
Ideally it would be nice to replace the location button with a `MKUserTrackingBarButtonItem`, but that would change the current behavior. `MKUserTrackingBarButtonItem` allows for map tracking with and without heading (which would probably expose the rotation bug). Currently the button just updates the location.

**Comment by bbodenmiller** [comment]
Do you have a before and after screenshot?

**Comment by yogipatel** [comment]
New:
new_icons
Old:
old_icons

**Comment by bbodenmiller** [comment]
Looks good. Do you happen to be interested in also tackling the fact that the location button always shows as solid even when not tracking the users current location?

**Comment by yogipatel** [comment]
Sure, #432.

**Pull request merged**
