### PR TITLE
WIP: Network stack enh.

### PR DESCRIPTION
**Pull request by beliyd**
Code for #303

This contains the final dev version of code, needs another pass of code review.

This code has been profiled though instruments with one adverse leak detected in existing code (added a #warning).

Please review at your convenience, I will update the Pull Request before it is ready for merge. 

During the refactor I also updated several places to modern objc. and removed some dead code.

### CODE REVIEW

**Comment by caitbonnar** [comment]
@Wizecoder @aaronbrethorst Any input for @beliyd here? 
Looks like you were close to finishing this -- it would be awesome to have this merged in (looks like it will take some rebasing first, unfortunately) for the next version if possible.

**Comment by aaronbrethorst** [comment]
@caitbonnar — I think the changes are expansive enough that I'd need to run it on my phone for a day or two to ensure that everything's ok. A cursory glance suggests everything's good, though.

@beliyd — can you fix the merge conflicts and give me a head's up when those changes are added to this PR? I'll check out your branch and then run it on my phone. Thanks!

**Comment by beliyd** [comment]
@aaronbrethorst I'll pull the parent and resolve conflicts on Saturday.  Thanks for testing this out!

**Comment by aaronbrethorst** [comment]
Thank you!

**Comment by aaronbrethorst** [comment]
@beliyd - any chance to bring your branch back in sync with `develop`?

**Comment by beliyd** [comment]
@aaronbrethorst working on it.

**Comment by aaronbrethorst** [comment]
Awesome, thanks!

**Comment by beliyd** [comment]
Pulled in the upstream & fixed a few clang warnings.

**Comment by aaronbrethorst** [comment]
@beliyd - I have your code running on my phone. I'll test it for the rest of the day and—if all goes well—get it merged in tomorrow or Thursday. Thanks!

**Comment by aaronbrethorst** [comment]
Looks good, merging. @beliyd — Thanks again!

**Pull request merged**
