### PR TITLE
Remove Google Dependencies

### PR DESCRIPTION
**Pull request by aaronbrethorst**
Removes all Google API dependencies from OBA for iOS.

### CODE REVIEW

**Comment by aaronbrethorst** [comment]
cc @barbeau

**Comment by barbeau** [comment]
Thanks @aaronbrethorst.  Is Google Maps used for anything in OBA iOS in the currently release, or is this just removing dead code?

**Comment by aaronbrethorst** [comment]
@barbeau we were using a Google Maps API to geocode addresses when the user performed an address search, but Apple has had this feature built in since iOS 6 without any usage limits, so I thought it made more sense to use what Apple offered, reduce external dependencies, and avoid usage limits. Here's the relevant diff https://github.com/OneBusAway/onebusaway-iphone/pull/1305/files#diff-9b0c079617a4cdd9ac1b1211a4a1b0d8R261

**Comment by barbeau** [comment]
👍

**Pull request merged**
