### PR TITLE
iOS 13 Support

### PR DESCRIPTION
**Pull request by ualch9**
This PR is a squashed version of #1445 

- Dark mode!
- Updated minimum target deployment from iOS 10.3 → iOS 11
- Updated tab bar icons to Material Icons
- Moved OBATheme named colors to the asset catalog (to support trait variations)
- Updated carthage dependencies

### CODE REVIEW

**Comment by ualch9** [comment]
# Dark Mode Screenshots

**Comment by ualch9** [comment]
@aaronbrethorst Please review.

**Comment by aaronbrethorst** [comment]
@ualch9 nice work, this looks awesome! I'm going to add this to my todo list to review tomorrow. Thanks for putting in all of this time and energy!

**Comment by aaronbrethorst** [comment]
@ualch9 great work. I'm merging this and will get a new TestFlight beta out as soon as I can. Couple things I noticed for you to keep an eye out for next time:

* Please use spaces instead of tabs in your editor. The indentation looks weird in the diffs when files switch between spaces and tabs. (see here for an example: https://github.com/OneBusAway/onebusaway-iphone/pull/1447/files#diff-945c563de747466bb2774c025df529c0R17)
* Please split out changes to Carthage checkouts into a separate commit—this makes it easier for me to focus on reviewing your changes.

thanks for investing all of this time and energy into the project! I'm looking forward to getting this into a new version of the app!

**Pull request merged**
