### PR TITLE
Fix #62 - Show stop icons at a higher zoom level

### LINKED ISSUE #62: Show stop icons at a higher (i.e., more zoomed out) zoom level
Originally referenced in #42.

The apps cuts off the view of icons at too low a zoom level.  Right now I'm several blocks from transit service that I wanted to look at, which requires me to zoom out, pan elsewhere, and then zoom back in to get stop icons to appear on the map.  And if I zoom out by a step or so, the icons disappear and again prompt me to "Zoom in to look for stops".  

In contrast, in the Android app I can zoom out to almost the city level and still get icons for all the stops on the map.

We should allow stop icons to be shown at least a few zoom levels higher than the current cutoff that triggers the "Zoom in to look for stops" prompt.

### PR DESCRIPTION
**Pull request by cagryInside**
I bump the zoom level.

The furthest zoom level looks like this in the app:

screen shot 2016-03-14 at 11 28 13 am

cc'd @barbeau

### CODE REVIEW

**Comment by barbeau** [comment]
@aaronbrethorst Could you please take a look and see if you're ok with this zoom level?  This is the zoom level PSTA is expecting to see stops at.

**Comment by aaronbrethorst** [comment]
@cagryInside is this sufficient for Tampa's needs?

**Comment by barbeau** [comment]
@aaronbrethorst Crossing messages :) - yes, this should be sufficient for Tampa.

**Comment by aaronbrethorst** [comment]
@barbeau @cagryInside great! this is totally fine from my perspective. the amount of data being used is still far less than what's required to send map tiles over the wire. i think this'll be a big win in terms of overall ux.

**Comment by aaronbrethorst** [comment]
@cagryInside Also, for future reference, you can press Command S in the Simulator to capture _only_ the Simulator's content with none of the window frame.

**Comment by aaronbrethorst** [comment]
:+1:

**Comment by barbeau** [comment]
:+1:  Thanks!

**Comment by cagryInside** [comment]
@aaronbrethorst This is the simulator screenshot:

simulator screen shot mar 14 2016 1 02 01 pm

**Pull request merged**
