### PR TITLE
Update Chinese translations

### PR DESCRIPTION
**Pull request by cathy810218**
Fixes https://github.com/OneBusAway/onebusaway-iphone/issues/1293 - Update Chinese translations

[Issue]
https://github.com/OneBusAway/onebusaway-iphone/issues/1293

[Description]
Update Chinese translations

### CODE REVIEW

**Comment by aaronbrethorst** [comment]
👍 thanks!

**Comment by barbeau** [comment]
@cathy810218 Just curious - do you know if there is a decent user base of OneBusAway Android that would benefit from a Chinese translation there?

**Comment by cathy810218** [comment]
@barbeau 
Hmm, I am actually not sure how many Chinese users are using OneBusAway. Most of the non-US people in the US would have their devices setup to use English. However, I do think that Chinese tourists would most likely find Chinese translations useful. :)
Let me know if you think that'd be a good idea to have Chinese translations on OBA Android.

**Comment by barbeau** [comment]
@cathy810218 I'm certainly open to adding the translation to OBA Android if you or someone else are willing to do/maintain the translation.

Translation work would be providing a Chinese version of:
* https://github.com/OneBusAway/onebusaway-android/blob/master/onebusaway-android/src/main/res/values/strings.xml
* https://github.com/OneBusAway/onebusaway-android/blob/master/onebusaway-android/src/main/res/values/arrays.xml

For example, Spanish is here:
* https://github.com/OneBusAway/onebusaway-android/blob/master/onebusaway-android/src/main/res/values-es/strings.xml
* https://github.com/OneBusAway/onebusaway-android/blob/master/onebusaway-android/src/main/res/values-es/arrays.xml

**Pull request merged**
