### PR TITLE
Fixing 404 link in Roadmap.md

### PR DESCRIPTION
**Pull request by kevinvanderlugt**
I was browsing around the project learning how to get started and found this 404 link.  
Easy way to start, would love to get more involved especially if there is a way to bring one bus away to apple watch.

Cheers!

### CODE REVIEW

**Comment by aaronbrethorst** [comment]
thanks, @kevinvanderlugt!

**Comment by aaronbrethorst** [comment]
and i'd love to see OBA on the Apple Watch sooner than later, too :)

**Comment by bbodenmiller** [comment]
Would OBA for watch would require similar library compartmentalization as the today widget?

**Comment by aaronbrethorst** [comment]
Yeah, I expect that they'll actually end up using the same extracted code.

**Pull request merged**
