### PR TITLE
Fix CI

### PR DESCRIPTION
**Pull request by ApolloZhu**
Update to use Xcode 11

### CODE REVIEW

**Comment by ApolloZhu** [comment]
```
error: Build input file cannot be found: '/Users/travis/build/OneBusAway/onebusaway-iphone/AppIdentities/GoogleService-Info.plist' (in target 'OneBusAway' from project 'org.onebusaway.iphone')
```

Since the application delegate for testing does not rely on Firebase, may we use a dummy plist to just make the build work?

**Comment by aaronbrethorst** [comment]
I think a dummy Firebase plist is a clever solution.

**Comment by ApolloZhu** [comment]
CI has passed

**Comment by aaronbrethorst** [comment]
🎉

**Comment by aaronbrethorst** [comment]
nice work @ApolloZhu!

**Pull request merged**
