### PR TITLE
Bookmark star

### PR DESCRIPTION
**Pull request by Wizecoder**
Added bookmark star, removed bookmark row, and replaced refresh icons with refresh controls. Currently the star uses the nav bar tint, and it actually looks kinda nice.

As per Issue #368 

ios simulator screen shot mar 10 2015 10 44 57 pm
ios simulator screen shot mar 10 2015 10 45 03 pm
ios simulator screen shot mar 10 2015 10 45 09 pm
ios simulator screen shot mar 10 2015 10 45 13 pm

### CODE REVIEW

**Comment by aaronbrethorst** [comment]
Needs to work on iOS 7, and needs 2x/3x graphics, but otherwise looks :+1:  I can take point on graphics after this is merged. iOS 7 support, though, is crucial.

**Comment by bbodenmiller** [comment]
@Wizecoder if you throw "fixes https://github.com/OneBusAway/onebusaway-iphone/issues/368" in the original PR message or one of the commits that issue will be automatically closed upon merge.

Additionally I think in a seperate PR we should remove the bottom redundant "About this stop" link.

**Comment by bbodenmiller** [comment]
Also I think these are good changes but they may be significant for our long time and not tech savvy users. I wonder if it may be time to raise the priority on the app tour feature request (https://github.com/OneBusAway/onebusaway-iphone/issues/193). Based on the work previously put together to introduce the stop info feature it appears it shouldn't be too hard and I imagine their is libraries to help with such a request.

**Comment by aaronbrethorst** [comment]
Given the previously poor discoverability of this feature, I'm not *that* concerned about moving this piece of UI for 2.4, but—@bbodenmiller—I think your concern is generally well-warranted, and I'd love to see some sort of comprehensive app tour feature introduced.

**Comment by bbodenmiller** [comment]
Good points. Unfortunately it does not appear we had analytics on the old button but we should be sure to add that to the new button.

**Comment by aaronbrethorst** [comment]
TODOs:

@Wizecoder 

- [ ] iOS 7 support
- [ ] Analytics

@aaronbrethorst (separately from this PR)

- [ ] 2x and 3x graphics

**Comment by yogipatel** [comment]
@Wizecoder @aaronbrethorst  I can wrap this up if that's ok. Anything specific you want for the analytics, or just the usual `button_press`/`Add Bookmark`, etc?

**Comment by aaronbrethorst** [comment]
`OBAGenericStopViewController` has been superseded.

**Pull request closed without merging**
