### PR TITLE
Fix issues with travis

### PR DESCRIPTION
**Pull request by aaronbrethorst**
* Update the required Cocoapods gem in the Gemfile (and README)
* Make the version requirement in the Podfile match the app
* Remove a now seemingly-unnecessary config setting in the Podfile

### CODE REVIEW

**Comment by chadsy** [comment]
👍

**Comment by chadsy** [comment]
🚢 :it: with the new cleanup & pods!

**Comment by aaronbrethorst** [comment]
👏 👏 👏 thanks man!

**Comment by barbeau** [comment]
Fyi - apparently there is a docker image for running Travis locally, if you
get to the point where trial and error remotely turns tortuous.  I've been
very close a few times, but haven't taken the dive yet.

**Comment by aaronbrethorst** [comment]
I did not know that. That's great to know, and I'll definitely keep it in mind. Hopefully I won't have to take that plunge :)

**Pull request merged**
