### PR TITLE
Overhaul UI for filtering departures

### PR DESCRIPTION
**Pull request by aaronbrethorst**
Move it to a segmented control toggle instead of a table cell that you tap.

* New static cell type: segmented control
* Plumb the segmented control into the Stop UI

### CODE REVIEW

**Comment by barbeau** [comment]
What does this look like on iOS?  I've been thinking about implementing on Android.

**Comment by aaronbrethorst** [comment]
@barbeau OLD:

img_1140

**Comment by aaronbrethorst** [comment]
@barbeau NEW:

simulator screen shot mar 12 2016 9 40 51 am

**Comment by barbeau** [comment]
Thanks!

**Comment by barbeau** [comment]
BTW - how are you doing the walk to stop distance/time?  Google Directions API?

**Comment by aaronbrethorst** [comment]
@barbeau stop distance and time are provided by Apple as part of their MapKit API. Here's some info about it: http://initwithfunk.com/blog/2014/02/14/you-dont-need-to-pay-google-to-get-directions-and-geocoding/

**Comment by barbeau** [comment]
@aaronbrethorst Ok, thanks.

And sorry, another question - what rules exactly are being used to filter out departures by default?

**Comment by aaronbrethorst** [comment]
@barbeau - there are no rules. it is entirely driven by the user. There's a "Filter & Sort Routes" option at the bottom of the view where the user can exclude routes that they don't want to see. By default, every route is displayed. This toggle only appears if the user has filtered at least one route.

**Comment by barbeau** [comment]
Ah, I see - so this option isn't to filter arrivals vs. departures, but just to filter out arrivals **AND** departures for certain routes.  In that case we do support this route filtering on Android.

On Android I'm trying to solve the problem of better differentiating arrival vs. departure info (general issue at https://github.com/OneBusAway/onebusaway-android/issues/287), and in the case of loop routes automatically filter out one of them (https://github.com/OneBusAway/onebusaway-android/issues/436).  The loop route issue is the more confusing and immediate issue I'm working on resolving.  I assume this also exists on iOS, then, although I don't think we have an issue open for it.  I'll open one shortly.

**Comment by barbeau** [comment]
New issue opened specifically for loop routes at https://github.com/OneBusAway/onebusaway-iphone/issues/562.

**Pull request merged**
